#!/bin/bash
# Remove leech/seed connections by country (useful for embargo countries like Russia - default)
#
# A default of Iran has been used as an example
#
# usage:    chia_remove "<country name>"
#
# Prerequisite - The chia python venv must have been sourced  ". ./activate" 
# Cache IP lookups (saves calls to db-ip)

file_IP=~/ips.txt
str_Country=${1:-"Russia"}
lst_IPS=$(chia show -c | grep ^FULL_NODE | cut -d" " -f2)
file_Cache=$(mktemp)

fn_ShowCountry()
{
  local IP=${1}
  local COUNTRY=
  if ! grep -q $IP ${file_IP} ; then
    printf "%15s\t$(curl -s http://api.db-ip.com/v2/free/${1} | grep -i countryname | awk -F":" '{print $NF}' )\n" ${each_IP}  >> ${file_IP}
  fi  
  COUNTRY=$(grep ${IP} ${file_IP})
  echo "${COUNTRY/,/}"
}

chia show -c > ${file_Cache}

touch $file_IP
# Generate Country cache list
for each_IP in $lst_IPS ; do
  printf "$(grep ${each_IP} ${file_Cache}) $(grep -A1 ${each_IP} ${file_Cache} | tail -1 | awk -F" " '{print $3}' ) $(fn_ShowCountry ${each_IP})\n"
  if [[ $(fn_ShowCountry ${each_IP}) =~ "${str_Country}" ]] ; then
    echo "Removing $(grep $each_IP ${file_IP})"
    str_NodeID=$(chia show -c | grep ${each_IP} | awk -F" " '{print $4}')
    chia show -r ${str_NodeID/.*/}
  fi
done
sort -k2 ${file_IP} > ${file_Cache}
mv ${file_Cache} ${file_IP}
